### ISSUE TITLE
got an unexpected keyword argument 'on_startup

### ISSUE THREAD

**Issue by rajathedgefinity** [Kludex/starlette#865]
app = Starlette(debug=True, routes=routes, on_startup = [startup])

documentation says to use on_startup, but it's not available in  app when i see with the help of app.
got an unexpected keyword argument 'on_startup

**Comment by euri10** [comment]
>   * **on_startup** - A list of callables to run on application startup.
 |  Startup handler callables do not take any arguments, and may be be either
 |  standard functions, or async functions.

**Comment by rajathedgefinity** [comment]
`from starlette.applications import Starlette
from starlette.responses import PlainTextResponse
from starlette.routing import Route, Mount, WebSocketRoute
from starlette.staticfiles import StaticFiles


def homepage(request):
    return PlainTextResponse('Hello, world!')

def user_me(request):
    username = "John Doe"
    return PlainTextResponse('Hello, %s!' % username)

def user(request):
    username = request.path_params['username']
    return PlainTextResponse('Hello, %s!' % username)

async def websocket_endpoint(websocket):
    await websocket.accept()
    await websocket.send_text('Hello, websocket!')
    await websocket.close()

async def start_up():
    print("Started")

routes = [
    Route('/', homepage),
    Route('/user/me', user_me),
    Route('/user/{username}', user),
    WebSocketRoute('/ws', websocket_endpoint),
    Mount('/static', StaticFiles(directory="static")),
]

app = Starlette(debug=True, routes=routes, on_startup=[start_up])
`

This Gives Me an Error as 
app = Starlette(debug=True, routes=routes, on_startup=[start_up])
TypeError: __init__() got an unexpected keyword argument 'on_startup'

**Comment by rajathedgefinity** [comment]
> > * **on_startup** - A list of callables to run on application startup.
> >   |  Startup handler callables do not take any arguments, and may be be either
> >   |  standard functions, or async functions.

Hello Euri I Tried an Example with what i go in documentaton it leads an Error., https://www.starlette.io/applications/ This is the Code

**Comment by euri10** [comment]
your code works fine, you may use an old Starlette version ?

**Comment by rajathedgefinity** [comment]
@euri10 Thank You euri10 Worked with Version 0.13.0 November 2019 Release. Is on_startup is deprecated in New Version ?
